sudo: false

language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

notifications:
  email: false

git:
  depth: 3

before_install:
  - sudo apt-get -qq update

install:
  - make deps

script:
  - make test

after_success:
  - make codecov
