sudo: false

language: go
go:
  - 1.9.x
  - 1.10.x

matrix:
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

notifications:
  email: false

git:
  depth: 3

before_install:
  - sudo apt-get -qq update

install:
  - make deps

script:
  - make test

after_success:
  - make codecov
