sudo: false

language: go
go:
  - 1.11.x
env:
  global:
    - GO111MODULE=on

matrix:
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

notifications:
  email: false

git:
  depth: 3

before_install:
  - sudo apt-get -qq update

install:
  - go mod download
  - make server_deps

script:
  - make test

after_success:
  - make codecov
