language: go
sudo: false
go:
  - "1.9.x"
  - "1.10"
  - tip

notifications:
  email: false

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - go get -u github.com/golang/dep/...

install:
  - make deps

script:
  - make test

after_success:
  - make codecov
